### ISSUE TITLE
error messages auf deutsch

### ISSUE THREAD

**Issue by Vetrox** [Vetrox/squirrelbot#25]

**Comment by roscha444** [comment]
Which error messages are meant here?
Could you maybe mention a few lines or the file?

For example, is the error meant here?
https://github.com/Vetrox/squirrelbot/blob/2fd858dcc3acefb5e786ae02c65c0f48cf8db389/modules/invite_manager.js#L133


and here?
https://github.com/Vetrox/squirrelbot/blob/2fd858dcc3acefb5e786ae02c65c0f48cf8db389/modules/chmgr.js#L648

Does this mean that all error messages sent to the user should be in German?
Then I could do that

**Comment by Vetrox** [comment]
**Yes please.** 

1. In errors.js are the generic error messages. At first you could change them to be in german.
2. In addition to that you could change every other character string, which will be displayed anywhere, to be german.
3. And finally console.log statements shouldn't be used, because they don't appear in the log.txt file. Instead all console.log statements should be either bot.api.log.logMessage or log.logMessage depending on the surrounding context.

If you feel like that needs several issues please create them and paste the corresponding part of the tasks in it.
