### ISSUE TITLE
api.js in externe Dateien auslagern

### ISSUE THREAD

**Issue by Baseng0815** [Vetrox/squirrelbot#88]
Ich habe in mehrstuendiger Arbeit versucht, die Klassen in api.js in externe Dateien auszulagern, es ist aber immer an irgendwelchen Dependencies gescheitert. Da ich keine Uebersicht mehr habe, waere es schoen, wenn diese Klassen in verschiedene Dateien ausgelagert und in einen api-Ordner gepackt werden.

**Comment by Vetrox** [comment]
branchname feat/api-split
