### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Baseng0815** [Vetrox/squirrelbot#89]
Add more descriptive error messages because this does not help much:
```
21/1/2021 21:58:6   [api]      KRITISCHER DATENBANK ERROR!!! chmgr_userchannels
```

This means modifying custom error types to take additional information and passing them properly when they are thrown. An example would be
```
21/1/2021 22:14:2   [api]      critical database error at 'chmgr_userchannels': BotError: param key length=6 not equal to this.keys.length=5
```

**Comment by roscha444** [comment]
in progress already #83 #85
